### ISSUE TITLE
xcb-cursor0, libxcb-cursor0 & QtMultimedia support

### ISSUE THREAD

**Issue by avttrue** [QuasarApp/CQtDeployer#801] opened 2024-03-04 12:07 UTC
build system: Ubuntu (KDE Neon 6, Wayland)
test system: Mint

1. Error: `qt.qpa.plugin: From 6.5.0, xcb-cursor0 or libxcb-cursor0 is needed to load the Qt xcb platform plugin.`
I tried to build: `cqtdeployer -bin MyApp -extraLibs libb2 xcb-cursor libxcb-cursor`
But as I understand it, the necessary libraries were not found. See logs.
[buildlog.txt](https://github.com/QuasarApp/CQtDeployer/files/14481057/buildlog.txt)
[verboselog.txt](https://github.com/QuasarApp/CQtDeployer/files/14481058/verboselog.txt)

2. For supporting QtMultimedia need to copy the plugins directory 'multimedia'. I'm doing it manually, is it possible to perform this operation using the deployer? upd: A! '-extraPlugin' - yes?

**Comment by EndrII** [comment] 2024-03-04 19:36
i think is duplicate of #779
it is Qt issue, please see #779

**Comment by EndrII** [comment] 2024-03-04 19:41
You have a syntax error on cqtdeployer command 

try this: 
```
-extraLibs "libb2,xcb-cursor"
```

For the multimedia, do nothing, because all plugins will be fetched automatically. IF you use qml do not forget set -qmlDir path/to/your/own/qml/code/root/folder

**Comment by avttrue** [comment] 2024-03-05 05:49
I understand about the extraLibs syntax, thank you. But regarding multimedia, this plugin is not including in the final package. Although it is necessary and the application does not start without it.

> plugins$ dir -h
> iconengines   networkinformation     platforms       printsupport  styles  wayland-shell-integration
> imageformats  platforminputcontexts  platformthemes  sqldrivers    tls     xcbglintegrations

[lddlog.txt](https://github.com/QuasarApp/CQtDeployer/files/14490979/lddlog.txt)

**Comment by EndrII** [comment] 2024-03-05 07:26
hmm, the multimedia plugin should copy automatically. But if you want to force copy it, just use the - -enablePlugins option 
```
cqtdeployer -enablePlugins multimedia
```

**Closed** 2024-03-06 09:28 UTC
Labels: Bug, Windows, Linux
